---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Data analysis for the All Coral Experiment #2021. Physiological variables:  
AFDW
Flow Cytometry (cell counts)
Protien
Biomass
BW
PAM


#Data and libraries
```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library('ggpubr')
library(lmerTest)
library(car)
library(emmeans)
```



#AFDW
```{r} 
# load in datasheets 
#Ashfreedryweight, Wax dipping, Total airbrush volume, metadata

AFDW <- read.csv("Data/AFDW_TT17_20190409.csv")

WaxDipping <- read.csv("Data/WaxDipping_Results_20190403.csv")
SA<-WaxDipping
SA<- SA[,c("Frag.ID","Surface.area")] # keep only columns you need


Slurry <- read.csv("Data/TT17_airbrush_totalVol_20190420.csv")
meta  <- read.csv("Data/Master_Metadata_20190402.csv")

# merge AFDW and slurry
AFDW.slurry <- merge(AFDW, Slurry)
AFDW.slurry$AFDW.mg.ml <- AFDW.slurry$AFDW.g.mL*1000  # grams to mg
AFDW.slurry$AFDWmg <-AFDW.slurry$AFDW.mg.ml*AFDW.slurry$TotalVolume # now we have mg of AFDW

# SA cm2 and AFDW g/mL --> mg/cm2

# merge
biomass <- merge(AFDW.slurry, SA)
biomass<- biomass[,c("Frag.ID", "AFDWmg", "Surface.area")] # keep only columns you need
biomass$AFDWmg.cm2 <-biomass$AFDWmg/biomass$Surface.area # mg/cm2

# merge with metadata to plot by treatments
biomass2 <- merge(biomass, meta)


# Mcap_biomass
biomass2_mean <- ddply(biomass2, c("Treatment", "Species", "Time.Point"), summarise, #summarize cell counts
                 N    = length(AFDWmg.cm2[!is.na(AFDWmg.cm2)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                 mean = mean(AFDWmg.cm2, na.rm=TRUE), #calculate mean of response variable, removing NA's
                 sd   = sd(AFDWmg.cm2, na.rm=TRUE), #calculate standard deviation
                 se   = sd / sqrt(N), #calculate standard error
                 max = max(AFDWmg.cm2, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
biomass2_mean #display table
#Mcap_biomass_mean <-Mcap_biomass_mean[-3,] # Remove T0
#biomass2_mean

# Make "BOTH" into Ambeint and High...THIS IS UGLY CODE BUT IT WORKS
# Mcap 
Mcap_biomass_mean<-subset(biomass2_mean, Species=="Montipora_capitata") #Subset Mcap

Mcap_biomass_mean_Both<-Mcap_biomass_mean #copy df
row.names.remove <- c("1","2","13","14") #remove high and amb by row numbers
Mcap_biomass_mean_Both<-Mcap_biomass_mean_Both[!(row.names(Mcap_biomass_mean_Both) %in% row.names.remove), ] #remove

Mcap_biomass_mean_Both2<-Mcap_biomass_mean_Both # make a copy of the BOTH df
Mcap_biomass_mean_Both[Mcap_biomass_mean_Both=="Both"]<-"Ambient"  #rename "Both" to "Ambient"
Mcap_biomass_mean_Both2[Mcap_biomass_mean_Both2=="Both"]<-"High"  #rename "Both" to "High"

row.names.remove <- c("9") #remove "high and amb by row numbers "both""
Mcap_biomass_mean<-Mcap_biomass_mean[!(row.names(Mcap_biomass_mean) %in% row.names.remove), ]
Mcap_biomass_mean<-rbind(Mcap_biomass_mean,Mcap_biomass_mean_Both,Mcap_biomass_mean_Both2) #bind together

# Pcomp 
Pcomp_biomass_mean<-subset(biomass2_mean, Species=="Porites_compressa") #Subset Pcomp

Pcomp_biomass_mean_Both<-Pcomp_biomass_mean #copy df
row.names.remove <- c("7","8","19","20") #remove high and amb by row numbers
Pcomp_biomass_mean_Both<-Pcomp_biomass_mean_Both[!(row.names(Pcomp_biomass_mean_Both) %in% row.names.remove), ] #remove

Pcomp_biomass_mean_Both2<-Pcomp_biomass_mean_Both # make a copy of the BOTH df
Pcomp_biomass_mean_Both[Pcomp_biomass_mean_Both=="Both"]<-"Ambient"  #rename "Both" to "Ambient"
Pcomp_biomass_mean_Both2[Pcomp_biomass_mean_Both2=="Both"]<-"High"  #rename "Both" to "High"

row.names.remove <- c("12") #remove "high and amb by row numbers "both""
Pcomp_biomass_mean<-Pcomp_biomass_mean[!(row.names(Pcomp_biomass_mean) %in% row.names.remove), ]
Pcomp_biomass_mean<-rbind(Pcomp_biomass_mean,Pcomp_biomass_mean_Both,Pcomp_biomass_mean_Both2) #bind together

# Pacu 
Pacu_biomass_mean<-subset(biomass2_mean, Species=="Pocillopora_acuta") #Subset Pacu

Pacu_biomass_mean_Both<-Pacu_biomass_mean #copy df
row.names.remove <- c("5","6","17","18") #remove high and amb by row numbers
Pacu_biomass_mean_Both<-Pacu_biomass_mean_Both[!(row.names(Pacu_biomass_mean_Both) %in% row.names.remove), ] #remove

Pacu_biomass_mean_Both2<-Pacu_biomass_mean_Both # make a copy of the BOTH df
Pacu_biomass_mean_Both[Pacu_biomass_mean_Both=="Both"]<-"Ambient"  #rename "Both" to "Ambient"
Pacu_biomass_mean_Both2[Pacu_biomass_mean_Both2=="Both"]<-"High"  #rename "Both" to "High"

row.names.remove <- c("11") #remove "high and amb by row numbers "both""
Pacu_biomass_mean<-Pacu_biomass_mean[!(row.names(Pacu_biomass_mean) %in% row.names.remove), ]
Pacu_biomass_mean<-rbind(Pacu_biomass_mean,Pacu_biomass_mean_Both,Pacu_biomass_mean_Both2) #bind together

# Pvar 
Pvar_biomass_mean<-subset(biomass2_mean, Species=="Pavona_varians") #Subset Pvar

Pvar_biomass_mean_Both<-Pvar_biomass_mean #copy df
row.names.remove <- c("3","4","15","16") #remove high and amb by row numbers
Pvar_biomass_mean_Both<-Pvar_biomass_mean_Both[!(row.names(Pvar_biomass_mean_Both) %in% row.names.remove), ] #remove

Pvar_biomass_mean_Both2<-Pvar_biomass_mean_Both # make a copy of the BOTH df
Pvar_biomass_mean_Both[Pvar_biomass_mean_Both=="Both"]<-"Ambient"  #rename "Both" to "Ambient"
Pvar_biomass_mean_Both2[Pvar_biomass_mean_Both2=="Both"]<-"High"  #rename "Both" to "High"

row.names.remove <- c("10") #remove "high and amb by row numbers "both""
Pvar_biomass_mean<-Pvar_biomass_mean[!(row.names(Pvar_biomass_mean) %in% row.names.remove), ]
Pvar_biomass_mean<-rbind(Pvar_biomass_mean,Pvar_biomass_mean_Both,Pvar_biomass_mean_Both2) #bind together



#Stats
# create dataframe with T0s turning into Amb and High. MAKE SURE THIS IS OK TO DO!

Biomass_stats<-biomass2
write.csv(Biomass_stats,"Biomass_stats.csv") #fixed by hand damn it

Biomass_stats2 <- read.csv("Biomass_stats.csv") #upload fixed <- not a solution dude. FIX IT



hist(Biomass_stats2$AFDWmg.cm2) 
Biomass_stats2$AFDWmg.cm2_log<-log10(Biomass_stats2$AFDWmg.cm2+1)
hist(Biomass_stats2$AFDWmg.cm2_log) #normal (use)

Biomass_model<-lmer(AFDWmg.cm2_log~Time.Point*Treatment*Species+(1|Parent.ID), Biomass_stats2)
anova(Biomass_model) 
qqPlot(residuals(Biomass_model)) 

  emm<-emmeans(Biomass_model,  ~ Time.Point*Treatment|Species, adjust="Tukey")
cld(emm)
pairs(emm)


###PLOTS

#plot Mcap
Mcap_biomass_plot<-ggplot(data=Mcap_biomass_mean, aes(x=Time.Point, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = F)+
  geom_line(aes(color=Treatment), linetype=2, show.legend = F)+
  scale_color_manual(values=c("dodgerblue3", "darkred"))+
  xlab("") + #Label the X Axis
  ylim(0, 10) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  ylab(expression(paste("Tissue biomass mg cm"^"-2"))) +
  ggtitle("Montipora capitata")+
  theme(plot.title = element_text(size=20, face = "italic"));Mcap_biomass_plot

# Pcomp 

Pcomp_biomass_plot<-ggplot(data=Pcomp_biomass_mean, aes(x=Time.Point, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = F)+
  geom_line(aes(color=Treatment), linetype=2, show.legend = F)+
  scale_color_manual(values=c("dodgerblue3", "darkred"))+
  xlab("") + #Label the X Axis
  ylab("") + #Label the X Axis
  ylim(0, 10) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  #ylab(expression(paste("Tissue biomass mg cm"^"-2"))) +
  ggtitle("Porites compressa")+
  theme(plot.title = element_text(size=20, face = "italic"));Pcomp_biomass_plot

# Pvar 

Pvar_biomass_mean_plot<-ggplot(data=Pvar_biomass_mean, aes(x=Time.Point, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = F)+
  geom_line(aes(color=Treatment), linetype=2, show.legend = F)+
  scale_color_manual(values=c("dodgerblue3", "darkred"))+
  xlab("") + #Label the X Axis
  ylim(2.5, 6) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        text = element_text(size=18),  # set element text
        plot.background =element_blank(), #Set the plot background
        legend.key = element_blank()) + #Set plot legend key
  ylab(expression(paste("Tissue biomass mg cm"^"-2"))) +
  ggtitle("Pavona varians")+
  theme(plot.title = element_text(size=20, face = "italic"));Pvar_biomass_mean_plot

# Pacu 

Pacu_biomass_mean_plot<-ggplot(data=Pacu_biomass_mean, aes(x=Time.Point, y=mean, group = Treatment, color=Treatment)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.1, show.legend = F)+
  geom_point(aes(color=Treatment), size=4, show.legend = F)+
  geom_line(aes(color=Treatment), linetype=2, show.legend = F)+
  scale_color_manual(values=c("dodgerblue3", "darkred"))+
  xlab("") + #Label the X Axis
  ylab("") + #Label the Y Axis
  ylim(0, 10) + #set Y limits
  theme_bw() + #Set the background color
  theme(axis.line = element_line(color = 'black'), #Set the axes color
        axis.title=element_text(size=14,face="bold"), #Set axis format
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        plot.background =element_blank(), #Set the plot background
        text = element_text(size=18),  # set element text
        legend.key = element_blank()) + #Set plot legend key
  #ylab(expression(paste("Tissue biomass mg cm"^"-2"))) +
  ggtitle("Pocillopora acuta")+
  theme(plot.title = element_text(size=20,face = "italic"));Pacu_biomass_mean_plot


###### All plots together

### NOTE YOU MAY NOT WANT TO INCLUDE T0. CONSIDER. 

AllPlots<-ggarrange(Mcap_biomass_plot, Pcomp_biomass_plot, Pacu_biomass_mean_plot, Pvar_biomass_mean_plot , 
                    labels = c("A", "B", "C", "D"),
                    ncol = 2, nrow = 2)

AllPlots
# save figures
ggsave("Figures/boiomass_2021.pdf", plot=AllPlots, height=8, width=10, units = c("in"), dpi=300) #output figure


```

# Flow cytometry  cell counts
```{r}
#import data
Std.curve <- read.csv("Data/standard_curve_fcm20181312.csv")

###notes: 2289 isn't anywhere. 

PlateA <- read.csv("Data/Symbio.Counts.Dec.14.2018.PlateA.csv")
PlateA <- subset(PlateA, Gate.Name == "Symbiodinium")       # keep only Symbiodinium rows
keepA <- c("Sample.Name", "Concentration") # keep only Sample.name and concentration
PlateA <- PlateA[keepA]
A_meta <- read.csv("Data/TT17_FC_PlateA.csv") # load Plate A location data
PlateA <- merge(PlateA, A_meta)   # merge with location data
PlateA <-merge(PlateA, meta, all.x = TRUE) # merge with Sample metadata
PlateA <- na.omit(PlateA) # omit NAs

PlateB <- read.csv("Data/Symbio.Counts.Dec.14.2018.PlateB1.csv")
PlateB$Concentration<-as.numeric(as.character(PlateB$Concentration)) # this is loading in as a factor, not sure why
PlateB <- subset(PlateB, Gate.Name == "Symbiodinium")
keepB <- c("Sample.Name", "Concentration")
PlateB <- PlateB[keepB]
B_meta <- read.csv("Data/TT17_FC_PlateB.csv") # lood Plate B location data
PlateB <- merge(PlateB, B_meta)
PlateB <-merge(PlateB, meta, all.x = TRUE)
PlateB <- na.omit(PlateB)

PlateC <- read.csv("Data/Symbio.Counts.Dec.14.2018.PlateCredo.csv")
PlateC$Concentration<-as.numeric(as.character(PlateC$Concentration)) # this is loading in as a factor, not sure why
PlateC <- subset(PlateC, Gate.Name == "Symbiodinium")
keepC <- c("Sample.Name", "Concentration")
PlateC <- PlateC[keepC]
C_meta <- read.csv("Data/TT17_FC_PlateCredo.csv") # lood Plate C location data
PlateC <- merge(PlateC, C_meta)
PlateC <-merge(PlateC, meta, all.x = TRUE)
PlateC <- na.omit(PlateC)
#note: Frag.ID 403 Pacu seems abnormally high

PlateE <- read.csv("Data/Symbio.Count.apr.02.2019.PlateE.csv")
PlateE$Concentration<-as.numeric(as.character(PlateE$Concentration)) # this is loading in as a factor, not sure why
PlateE <- subset(PlateE, Gate.Name == "Symbiodinium")
keepE <- c("Sample.Name", "Concentration")
PlateE <- PlateE[keepE]
E_meta <- read.csv("Data/TT17_FC_PlateE.csv") # lood Plate A location data
PlateE <- merge(PlateE, E_meta)
PlateE <-merge(PlateE, meta, all.x = TRUE)
PlateE <- na.omit(PlateE)


# Bind all runs together
tData <- rbind(PlateA, PlateB, PlateC, PlateE)
tData$Parent.ID<- as.factor(tData$Parent.ID) #for some reason, "Concentration" was a chr not numeric. Check by calling str()

# Create column to relate to standard curve
tData$corrected <- tData$Concentration*3.2959 # <- also confirm you did this correctly. 

# Use Slurry
#merge with tdata
tData <- merge(tData, Slurry)
tData$TotalVolume <- tData$TotalVolume * 1000 # change total volume to from mL to uL

#use SA for slurry

#merge with tData, make numeric
tData <- merge(tData, SA)
tData$Surface.area<- as.numeric(as.character(tData$Surface.area))

#Subset by Species and correct for 10% dilutions in Mcap and Pcomp
Mcap_FC <- subset(tData, Species == "Montipora_capitata")
Mcap_FC$corrected <- Mcap_FC$corrected*10 # to compensate for the 10% dultion

Pcomp_FC <- subset(tData, Species == "Porites_compressa")
Pcomp_FC$corrected <- Pcomp_FC$corrected*10 # to compensate for the 10% dultion

Pvar_FC <- subset(tData, Species == "Pavona_varians") #not diluted
Pacu_FC <- subset(tData, Species == "Pocillopora_acuta") #not diluted

# Create new column for total cells in total slurry
Mcap_FC$Tot.zoox <- Mcap_FC$corrected*(Mcap_FC$TotalVolume)
Pcomp_FC$Tot.zoox <- Pcomp_FC$corrected*(Pcomp_FC$TotalVolume)
Pvar_FC$Tot.zoox <- Pvar_FC$corrected*(Pvar_FC$TotalVolume)
Pacu_FC$Tot.zoox <- Pacu_FC$corrected*(Pacu_FC$TotalVolume)

# Calculate zoox/cm2
Mcap_FC$zoox.cm2<-Mcap_FC$Tot.zoox/Mcap_FC$Surface.area
Pcomp_FC$zoox.cm2<-Pcomp_FC$Tot.zoox/Pcomp_FC$Surface.area
Pvar_FC$zoox.cm2<-Pvar_FC$Tot.zoox/Pvar_FC$Surface.area
Pacu_FC$zoox.cm2<-Pacu_FC$Tot.zoox/Pacu_FC$Surface.area

oData <- rbind(Mcap_FC, Pcomp_FC, Pvar_FC, Pacu_FC) #combine

#analyze
############## BY corrected to st curve and zoox.cm2

#mean tables
# Mcap
Mcap_FC_Sum <- ddply(Mcap_FC, c("Treatment", "Species", "Time.Point"), summarise, #summarize cell counts
                   N    = length(zoox.cm2[!is.na(zoox.cm2)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                   mean = mean(zoox.cm2, na.rm=TRUE), #calculate mean of response variable, removing NA's
                   sd   = sd(zoox.cm2, na.rm=TRUE), #calculate standard deviation
                   se   = sd / sqrt(N), #calculate standard error
                   max = max(zoox.cm2, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
Mcap_FC_Sum #display table

# Pcomp
Pcomp_FC_Sum <- ddply(Pcomp_FC, c("Treatment", "Species", "Time.Point"), summarise, #summarize cell counts
                   N    = length(zoox.cm2[!is.na(zoox.cm2)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                   mean = mean(zoox.cm2, na.rm=TRUE), #calculate mean of response variable, removing NA's
                   sd   = sd(zoox.cm2, na.rm=TRUE), #calculate standard deviation
                   se   = sd / sqrt(N), #calculate standard error
                   max = max(zoox.cm2, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
Pcomp_FC_Sum #display table


# Pvar
Pvar_FC_Sum <- ddply(Pvar_FC, c("Treatment", "Species", "Time.Point"), summarise, #summarize cell counts
                   N    = length(zoox.cm2[!is.na(zoox.cm2)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                   mean = mean(zoox.cm2, na.rm=TRUE), #calculate mean of response variable, removing NA's
                   sd   = sd(zoox.cm2, na.rm=TRUE), #calculate standard deviation
                   se   = sd / sqrt(N), #calculate standard error
                   max = max(zoox.cm2, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
Pvar_FC_Sum #display table

# Pacu
Pacu_FC_Sum <- ddply(Pacu_FC, c("Treatment", "Species", "Time.Point"), summarise, #summarize cell counts
                   N    = length(zoox.cm2[!is.na(zoox.cm2)]), #calculate the length of the data frame, excluding NA’s *this part is important*
                   mean = mean(zoox.cm2, na.rm=TRUE), #calculate mean of response variable, removing NA's
                   sd   = sd(zoox.cm2, na.rm=TRUE), #calculate standard deviation
                   se   = sd / sqrt(N), #calculate standard error
                   max = max(zoox.cm2, na.rm=TRUE) #calculate max, could also calculate min () if desired
)
Pacu_FC_Sum #display table


#Bar plots
par(mfrow=c(2,2))

#Mcap
Mcap_FC_Plot<-ggplot(data=Mcap_FC_Sum, aes(x=Time.Point, y=mean, fill= Treatment)) +
  scale_fill_manual(values=c("blue", "purple","red"))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.05, position=position_dodge(0.9))+
  theme_classic()+
  theme(text = element_text(size = 18, color="black"))+
  theme(axis.text = element_text(size = 18))+
  theme(axis.title = element_text(size = 18))+
  ylab(expression(paste("Symbiodinaceae (cells cm-2"))) +
  ggtitle("Montipora capitata");Mcap_FC_Plot

#ggsave("Figures/Mcap_20181222.pdf", plot=McapPlot, height=8, width=10, units = c("in"), dpi=300) #output figure


#Pcomp
Pcomp_FC_Plot<-ggplot(data=Pcomp_FC_Sum, aes(x=Time.Point, y=mean, fill= Treatment)) +
  scale_fill_manual(values=c("blue", "purple","red"))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.05, position=position_dodge(0.9))+
  theme_classic()+
  theme(text = element_text(size = 18, color="black"))+
  theme(axis.text = element_text(size = 18))+
  theme(axis.title = element_text(size = 18))+
  ylab(expression(paste("Symbiodinaceae (cells cm-2)"))) +
  ggtitle("Porites compressa");Pcomp_FC_Plot


#ggsave("Figures/Pcomp_20181222.pdf", plot=PcompPlot, height=8, width=10, units = c("in"), dpi=300) #output figure

#Pvar
Pvar_FC_Plot<-ggplot(data=Pvar_FC_Sum, aes(x=Time.Point, y=mean, fill= Treatment)) +
  scale_fill_manual(values=c("blue", "purple","red"))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.05, position=position_dodge(0.9))+
  theme_classic()+
  theme(text = element_text(size = 18, color="black"))+
  theme(axis.text = element_text(size = 18))+
  theme(axis.title = element_text(size = 18))+
  ylab(expression(paste("Symbiodinaceae (cells cm-2)"))) +
  ggtitle("Pavona varians");Pvar_FC_Plot

#ggsave("Figures/Pvar_20181222.pdf", plot=PvarPlot, height=8, width=10, units = c("in"), dpi=300) #output figure

#Pacu
Pacu_FC_Plot<-ggplot(data=Pacu_FC_Sum, aes(x=Time.Point, y=mean, fill= Treatment)) +
  scale_fill_manual(values=c("blue", "purple","red"))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=0.05, position=position_dodge(0.9))+
  theme_classic()+
  theme(text = element_text(size = 18, color="black"))+
  theme(axis.text = element_text(size = 18))+
  theme(axis.title = element_text(size = 18))+
  ylab(expression(paste("Symbiodinaceae (cells cm-2)"))) +
  ggtitle("Pocillopora acuta");Pacu_FC_Plot


#ggsave("Figures/Pacu_20181222.pdf", plot=PacuPlot, height=8, width=10, units = c("in"), dpi=300) #output figure


# just plot again
par(mfrow=c(2,2))
Mcap_FC_Plot
Pcomp_FC_Plot
Pvar_FC_Plot
Pacu_FC_Plot










START here with code for plotting together. 

  
  
  
  
)```

# 
