---
title: "ACE21_overview_figure"
author: "Shayle Matsuda"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Combine Physio, ITS2, and 16S

Load libraries
```{r cars}
library(ggbiplot)
require(graphics)
library(tidyr)
library(vegan)



library(plyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(lmerTest)
library(car)
library(emmeans)
library(gridExtra)
library(multcomp)
library(reshape)
library(tidyverse)
library(factoextra)
library(reshape2)
library(vegan)
library(pairwiseAdonis)
library("scales")
packageVersion("scales")
library(RColorBrewer)
library(colorRamps)
library(devtools)
library(tidyverse)
```

Load data

```{r}
physio<-read.csv("PhysioData.csv")
    physio$sample.id<-as.factor(physio$sample.id)  #change to tidy language when you have time. 
     physio$treatment<-as.factor(physio$treatment)
      physio$species<-as.factor(physio$species)
            physio$parent.ID<-as.factor(physio$parent.ID)
        physio$time.point<-as.factor(physio$time.point)
                physio$code<-as.factor(physio$code)
                physio$size<-as.factor(physio$size)
            physio$clade<-as.factor(physio$clade)
                        physio$repro.mode<-as.factor(physio$repro.mode)
                        physio$sex<-as.factor(physio$sex)
                        physio$repro.mode<-as.factor(physio$repro.mode)
                    physio$tank.num<-as.factor(physio$tank.num)
                            physio$transmission<-as.factor(physio$transmission)
                                physio$skeletal.density<-as.factor(physio$skeletal.density)
                                    physio$shape<-as.factor(physio$shape)
                   
                            
its2<-read.csv("ITS2_T0_nmds.scores.csv")
    its2$sample.id<-as.factor(its2$sample.id)
its2.nmds1_T0<-subset(its2,its2$Time.Point=="T0")
its2.nmds1_T0<-its2.nmds1_T0[, c("sample.id", "ITS2.NMDS1")]


bacteria<-read.csv("16s_nmds.scores.ord.u_RelA_stats.T0.csv") #only T0
    names(bacteria)[1]<-"sample.id"
    bacteria$sample.id<-as.factor(bacteria$sample.id)
# bacteria_T0<-subset(bacteria,bacteria$Time.Point=="T0")
bacteria.nmds1<-bacteria[, c("sample.id", "bac.NMDS1")]
#remove duplicates 


#combine 16s and ITS with physio

df<-merge(physio, bacteria.nmds1, by="sample.id")   
   df<-merge(df, its2.nmds1_T0, by="sample.id")   
  df<-na.omit(df) #remove rows with NAs in any trait
  
  df$respiration<-df$respiration*-1 #make resp positive

  
  
#### make df with just a priori data
  library(mcmc)
phy.apriori<-df[,c(1,3,5:15)]
  
   MCMCmixfactanal()
```

```{r}
# center data
df.scale <- prcomp(df[c(12:23)], center = TRUE, scale = TRUE) #center and scale
summary(df.scale)
 
str(df.scale)

ggbiplot(df.scale) #quick look at plot

#exract scores for gg
Miss_scores <- as.data.frame(df.scale$x)
Miss_scores$sample.id <- df$sample.id
Miss_scores$parent.ID <- df$parent.ID
Miss_scores$treatment <- df$treatment
Miss_scores$species <- df$species
Miss_scores$clade <- df$clade
Miss_scores$transmission <- df$transmission
Miss_scores$skeletal.density <- df$skeletal.density
Miss_scores$size <- df$size


#Plot
ggplot(Miss_scores, aes(x = PC1, y= PC2)) + geom_point(aes(colour = species, shape = species), size = 4) +
  stat_ellipse(aes(x = PC1, y = PC2, colour = species), linetype = 2) +
  theme_classic()

plot<-ggbiplot(df.scale,
         ellipse = T, groups=df$species) 
plot +theme_classic()










apData<-PhysioData #make a copy
apData$Respiration<-apData$Respiration*-1 #make respiration all positive
apData<-subset(apData, Time.Point=="T1"|Time.Point=="TF") #only T1 and TF
apData<-na.omit(apData) #remove NAs
apData<-apData[,c("Parent.ID","Treatment","Species", "Time.Point", "Calcification","AFDWmg.cm2","zoox.cm2_log","Chl a","Protein", "Yield","Photosynthesis", "Respiration","PR")] #put cols in correct order

apData2 <- prcomp(apData[c(5:13)], center = TRUE, scale = TRUE) #center and scale
summary(apData2)
 
str(apData2)

ggbiplot(apData2) #quick look at plot

#exract scores for gg
Miss_scores <- as.data.frame(apData2$x)
Miss_scores$frag.id <- apData$Frag.ID
Miss_scores$parent.id <- apData$Parent.ID
Miss_scores$treatment <- apData$Treatment
Miss_scores$species <- apData$Species
Miss_scores$time.point <- apData$Time.Point


#Plot
ggplot(Miss_scores, aes(x = PC1, y= PC2)) + geom_point(aes(colour = species, shape = time.point), size = 4) +
  stat_ellipse(aes(x = PC1, y = PC2, colour = species), linetype = 2) +
  theme_classic()

#plot by time and species
Miss_scores$treatSpecies<-paste0(Miss_scores$species, Miss_scores$treatment )
Miss_scores$treatTime<-paste0(Miss_scores$treatment, Miss_scores$time.point )

ggplot(Miss_scores, aes(x = PC1, y= PC2)) + geom_point(aes(colour = species, shape = time.point), size = 4) +
  stat_ellipse(aes(x = PC1, y = PC2, colour = treatSpecies), linetype = 2) +
  theme_classic()

```



 Try MCoA http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/114-mca-multiple-correspondence-analysis-in-r-essentials/
```{r}
library("FactoMineR")
library("factoextra")


```
 
 